# Generated by Django 5.2.1 on 2025-05-31 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Adicional')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido_cliente', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID do Pedido (Cliente)')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Cliente')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('enviado_whatsapp', models.BooleanField(default=False, verbose_name='Enviado para WhatsApp')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Sabor')),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço Base')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagens/', verbose_name='Imagem do Produto')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('adicionais_disponiveis', models.ManyToManyField(blank=True, to='menu.adicional', verbose_name='Adicionais Disponíveis')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='menu.categoria', verbose_name='Categoria')),
                ('sabores_disponiveis', models.ManyToManyField(blank=True, to='menu.sabor', verbose_name='Sabores Disponíveis')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário no Momento da Compra')),
                ('subtotal_adicionais', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Subtotal Adicionais')),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal do Item')),
                ('adicionais_selecionados', models.ManyToManyField(blank=True, to='menu.adicional', verbose_name='Adicionais Selecionados')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='menu.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.produto', verbose_name='Produto')),
                ('sabores_selecionados', models.ManyToManyField(blank=True, to='menu.sabor', verbose_name='Sabores Selecionados')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
