# Generated by Django 5.2.1 on 2025-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Defina a ordem (ex: 0, 1, 2...). Categorias com números menores aparecem primeiro.', verbose_name='Ordem de Exibição'),
        ),
    ]
