# Generated by Django 5.2.1 on 2025-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_categoria_options_categoria_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf_cliente',
            field=models.CharField(blank=True, help_text='Ex: 000.000.000-00', max_length=14, null=True, verbose_name='CPF do Cliente (Opcional)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão (Débito/Crédito)'), ('dinheiro', 'Dinheiro')], default='dinheiro', max_length=10, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precisa de troco para'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Completo do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais do Pedido'),
        ),
    ]
