# Generated by Django 5.2.1 on 2025-06-17 18:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_pedido_cpf_cliente_alter_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Adicional', 'verbose_name_plural': 'Adicionais'},
        ),
        migrations.AlterModelOptions(
            name='sabor',
            options={'ordering': ['nome'], 'verbose_name': 'Sabor', 'verbose_name_plural': 'Sabores'},
        ),
        migrations.AddField(
            model_name='adicional',
            name='tipo',
            field=models.CharField(choices=[('SECO', 'Seco / Sólido'), ('COBERTURA', 'Cobertura / Calda'), ('FRUTA', 'Fruta'), ('OUTRO', 'Outro')], default='SECO', max_length=10, verbose_name='Tipo de Adicional'),
        ),
        migrations.AddField(
            model_name='sabor',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preço extra para este sabor (deixe 0 se não tiver custo adicional).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Extra'),
        ),
    ]
