# Generated by Django 5.2.1 on 2025-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_adicional_options_alter_sabor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='tipo',
            field=models.CharField(choices=[('SECO', 'Adicionais'), ('COBERTURA', 'Cobertura'), ('FRUTA', 'Fruta'), ('OUTRO', 'Outro')], default='SECO', max_length=10, verbose_name='Tipo de Adicional'),
        ),
    ]
